<?php

return [

    'keywords' => [
        // Financial/Scam
        'money',
        'crypto',
        'bitcoin',
        'blockchain',
        'investment',
        'forex',
        'trading',
        'nft',
        'cash',
        'loan',
        'earn',
        'income',
        'profit',
        'revenue',
        'finance',
        'withdraw',
        'payment',
        'payout',
        'bonus',
        'deposit',

        // Marketing/Sales
        'seo',
        'boost',
        'rank',
        'traffic',
        'backlink',
        'targeted ads',
        'promotion',
        'optimize',
        'marketing',
        'click here',
        'guaranteed',
        'limited time offer',
        'grow your business',
        'get customers',
        'site audit',
        'increase leads',
        'ad campaign',
        'affordable price',

        // Phishing/Scare Tactics
        'your account',
        'password reset',
        'urgent',
        'warning',
        'alert',
        'verify now',
        'fix your site',
        'google maps',
        'disabled account',
        'security alert',
        'login required',

        // Language patterns
        'hello i am',
        'i wrote about',
        'contact me',
        'price list',
        'reseller',
        'i need your',
        'i want to know',
        'cheap prices',

        // Spammy phrases/links
        'bit.ly',
        'tinyurl',
        'goo.gl',
        'click below',
        'buy now',
        'signup now',
        'free trial',
        'special offer',
        'lowest price',
        'visit my website',
        'free download',
        'access now',
        'limited offer',
        'watch video',

        // Suspicious messages
        'clear your links',
        'toxic backlinks',
        'whatsapp me',
        'remove negative reviews',
        '5-star rating',
        'social ads traffic',
        'adult content',
        'viagra',
        'lottery',
        'casino',
        'porn',

        // Foreign spam phrases
        'Здравствуйте',
        'увеличу посещаемость',
        'заработок',
        'roeddwn i eisiau',
        'ego volo scire',
        'ndewo',
        'achọrọ m',

        // Generic spammy words
        'newsletter',
        'subscribe',
        'web traffic',
        'email list',
        'email blast',

        'let’s talk',
        'message me',
        'get along',
        'click here',
        'check this out',
        'rb.gy',
        'bit.ly',
        'tinyurl',
        'is.gd',

    ],

    'blacklist_domains' => [
        'mail.ru',
        'inbox.ru',
        'list.ru',
        'bk.ru',
        'protonmail.com',
        'tutanota.com',
        'cock.email',
        'xyz',
        'unlimitedclientengine.com',
        'professionalseocleanup.com',
        'monkeydigital.co',
        'seoexpert.com',
        'marketingboost.net',
        'fastwebmail.com',
        'onlinemarketing.com',
        'cheaptraffic.net',
        'trafficboost.org',
        'boostseo.ai',
        'gmail.ru',
        'yahoo.ru',
        'rb.gy',
        'bit.ly',
        'tinyurl.com',
        'is.gd',

        'spublishers.com',
        'mailinator.com',
        'do-not-respond.me',
        'rambler.ru',
        'msn.com',
        'tutamail.com',
        'dynainbox.com',
        'tokyo.jp',
        'googlemail.com',
        '24red.ru',
        'digitalxflow.com',
        'strictlydigital.net',
        'hullboxandpack.co.uk',
        'digital-x-press.com',
        'sendnow.win',
        'pawtrim.shop',
        'medicopostura.com',
        'bangeshop.com',
        'techsite-new.store',

    ],

    'blacklist_emails' => [
        'garylimjap@gmail.com',
        'info@spublishers.com',
        'qujubixe@mailinator.com',
        'mikexxxx@gmail.com',
        'kinggreensony@gmail.com',
        'csam59454@gmail.com',
        'hello@unlimitedclientengine.com',
        'raya.gritsenko.91@mail.ru',
        'ebojajuje04@gmail.com',
        'ibucezevuda439@gmail.com',
        'yooourmail@gmail.com',
        'info@professionalseocleanup.com',
        'raymondSokvoido@gmail.com',
        'amandaIromBeamb@gmail.com',
        'moqagides18@gmail.com',
        'yawiviseya67@gmail.com',
        'llcm9375@gmail.com',
        'allanmukuni@bilta.org',
        'allanmukuni@yahoo.com',
        'mike@monkeydigital.co',
        'qasimyaseen326@gmail.com',
        'norine.schiller@gmail.com',
        'sales@hullboxandpack.co.uk',
        'ashley.mable@gmail.com',
        'speedyindexbot@gmail.com',
        'info@omalley.medicopostura.com',
        'info@digitalxflow.com',
        'trent.francesca@gmail.com',
        'latimer.levi@gmail.com',
        'trinidad.kinard@hotmail.com',
        'info@strictlydigital.net',
        'info@joseph.caredogbest.com',
        'info@chadwick.caredogbest.com',
        'dobyfinancial@sendnow.win',
        'warrobots@gmail.com',
        'info@speed-seo.net',
        'info@poston.bangeshop.com',
        '1win@gmail.com',
        'micahnamfukwe7@gmail.com',
        'anepivepaz038@gmail.com',
        'romabookim@gmail.com',
        'futgrghb@do-not-respond.me',
        'kitsuper@techsite-new.store',
        'mireya.peel@yahoo.com',
        'rohtopharmaceutical@via.tokyo.jp',
        'info@mata.pawtrim.shop',
        'info@mcelhaney.pawtrim.shop',
        'waggoner.estela@gmail.com',
        'balke.valorie@msn.com',
        'latoyapeterson64@yahoo.com',
        'hester.hanger@gmail.com',
        'uwe.willison@hotmail.com',
        'justus.alton24@gmail.com',
        'annette.harold@outlook.com',
        'alex01@24red.ru',
        'ocopesuq299@gmail.com',
        'marketerzseo@gmail.com',
        'elena_malaeva@rambler.ru',
        'amandaIromBeam3@gmail.com',
        'stenlyPap@gmail.com',
        'sparrow.eli@googlemail.com',
        'amandaIromBeam2@gmail.com',
        'rtppshnu@do-not-respond.me',
        'duqotayowud23@gmail.com',
        'kk69000@gmail.com',
        'joannariggs278@gmail.com',
        'zeen.localnews@gmail.com',
        'tiarastover3@gmail.com',
        'smithsean77@gmail.com',
        'nomin.momin+227u2@mail.ru',
        'ameliabrown5822@gmail.com',
        'greeting@gmail.com',
        'aferinohis056@gmail.com',
        'info@digital-x-press.com',
        'joshuawright1972@tutamail.com',
        'chalifoux_strength@biebel54.dynainbox.com',
        'zekisuquc419@gmail.com',
        'c302225@gmail.com',
        'xiceruxuk02@gmail.com'
    ]

];
